/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import java.awt.Component;
import java.util.Arrays;
import javax.swing.JList;
import source.AFND;

/**
 *
 * @author gabif
 */
public class MenuGUI extends javax.swing.JPanel {
    
    private final AFND afnd;
    /**
     * Creates new form MenuGUI
     * @param afnd
     */
    public MenuGUI(AFND afnd) {
        initComponents();
        this.afnd = afnd;
        this.novoSimb.setText("");
        this.novoQ.setText("");
        this.novoF.setText("");
        this.atualizaListaEstados();
    }
    
    @Override
    public void updateUI() {
        super.updateUI(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        if(this.afnd != null)atualizaTudo();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        AddDados = new javax.swing.JPanel();
        labelAddSimb = new javax.swing.JLabel();
        labelAddQ = new javax.swing.JLabel();
        labelAddF = new javax.swing.JLabel();
        novoSimb = new javax.swing.JTextField();
        novoQ = new javax.swing.JTextField();
        novoF = new javax.swing.JTextField();
        buttonAddSimb = new javax.swing.JButton();
        buttonAddEstado = new javax.swing.JButton();
        buttonAddEstadoFinal = new javax.swing.JButton();
        AddTransicoes = new javax.swing.JPanel();
        labelAddTransicao = new javax.swing.JLabel();
        labelEstadoAtual = new javax.swing.JLabel();
        labelSimbLido = new javax.swing.JLabel();
        labelNovosEstados = new javax.swing.JLabel();
        buttonAddTransicao = new javax.swing.JButton();
        scrollEstadosAtual = new javax.swing.JScrollPane();
        listaEstadosAtual = new javax.swing.JList<>();
        scrollSimbAlfabeto = new javax.swing.JScrollPane();
        listaSimbAlfabeto = new javax.swing.JList<>();
        scrollNovosEstados = new javax.swing.JScrollPane();
        listaNovosEstados = new javax.swing.JList<>();
        VisualizaTransicoes = new javax.swing.JPanel();
        labelVerTransicoes = new javax.swing.JLabel();
        scrollTransicoesCad = new javax.swing.JScrollPane();
        listaTransicoesCad = new javax.swing.JList<>();
        buttonConverte = new javax.swing.JButton();
        labelEstadoInicial = new javax.swing.JLabel();
        labelEstadoQ0 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Criando o Autômato Finito Não Determinístico (AFND)");

        labelAddSimb.setText("Adicionar símbolo ao alfabeto:");

        labelAddQ.setText("Adicionar estado ao conjunto de estados:");

        labelAddF.setText("Adicionar estado ao conjunto de estados Finais:");

        novoSimb.setText("Alfa");
        novoSimb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoSimbActionPerformed(evt);
            }
        });

        novoQ.setText("Q");

        novoF.setText("F");

        buttonAddSimb.setText("AddSimb");
        buttonAddSimb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddSimbActionPerformed(evt);
            }
        });

        buttonAddEstado.setText("AddEstado");
        buttonAddEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddEstadoActionPerformed(evt);
            }
        });

        buttonAddEstadoFinal.setText("AddFinal");
        buttonAddEstadoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddEstadoFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddDadosLayout = new javax.swing.GroupLayout(AddDados);
        AddDados.setLayout(AddDadosLayout);
        AddDadosLayout.setHorizontalGroup(
            AddDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddDadosLayout.createSequentialGroup()
                        .addComponent(novoF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAddEstadoFinal))
                    .addComponent(labelAddF)
                    .addGroup(AddDadosLayout.createSequentialGroup()
                        .addComponent(novoQ, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAddEstado))
                    .addComponent(labelAddQ)
                    .addGroup(AddDadosLayout.createSequentialGroup()
                        .addComponent(novoSimb, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAddSimb))
                    .addComponent(labelAddSimb))
                .addContainerGap())
        );

        AddDadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonAddEstado, buttonAddEstadoFinal, buttonAddSimb});

        AddDadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelAddF, labelAddQ, labelAddSimb});

        AddDadosLayout.setVerticalGroup(
            AddDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAddSimb)
                .addGap(18, 18, 18)
                .addGroup(AddDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoSimb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddSimb))
                .addGap(18, 18, 18)
                .addComponent(labelAddQ)
                .addGap(18, 18, 18)
                .addGroup(AddDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddEstado))
                .addGap(18, 18, 18)
                .addComponent(labelAddF)
                .addGap(18, 18, 18)
                .addGroup(AddDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddEstadoFinal))
                .addContainerGap())
        );

        AddDadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {novoF, novoQ, novoSimb});

        AddDadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonAddEstado, buttonAddEstadoFinal, buttonAddSimb});

        AddDadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelAddF, labelAddQ, labelAddSimb});

        labelAddTransicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAddTransicao.setText("Adicionar transição:");

        labelEstadoAtual.setText("Estado Atual");

        labelSimbLido.setText("Símbolo Lido");

        labelNovosEstados.setText("Novo(s) Estado(s)");

        buttonAddTransicao.setText("AddTransição");
        buttonAddTransicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddTransicaoActionPerformed(evt);
            }
        });

        listaEstadosAtual.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollEstadosAtual.setViewportView(listaEstadosAtual);

        listaSimbAlfabeto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollSimbAlfabeto.setViewportView(listaSimbAlfabeto);

        scrollNovosEstados.setViewportView(listaNovosEstados);

        javax.swing.GroupLayout AddTransicoesLayout = new javax.swing.GroupLayout(AddTransicoes);
        AddTransicoes.setLayout(AddTransicoesLayout);
        AddTransicoesLayout.setHorizontalGroup(
            AddTransicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTransicoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddTransicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddTransicoesLayout.createSequentialGroup()
                        .addGroup(AddTransicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelEstadoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollEstadosAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddTransicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(buttonAddTransicao)
                            .addComponent(scrollSimbAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSimbLido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddTransicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelNovosEstados)
                            .addComponent(scrollNovosEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelAddTransicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        AddTransicoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {scrollEstadosAtual, scrollNovosEstados, scrollSimbAlfabeto});

        AddTransicoesLayout.setVerticalGroup(
            AddTransicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTransicoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAddTransicao)
                .addGap(22, 22, 22)
                .addGroup(AddTransicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstadoAtual)
                    .addComponent(labelSimbLido)
                    .addComponent(labelNovosEstados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddTransicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrollNovosEstados)
                    .addComponent(scrollSimbAlfabeto)
                    .addComponent(scrollEstadosAtual))
                .addGap(36, 36, 36)
                .addComponent(buttonAddTransicao)
                .addContainerGap())
        );

        labelVerTransicoes.setText("Transições cadastradas:");

        scrollTransicoesCad.setViewportView(listaTransicoesCad);

        javax.swing.GroupLayout VisualizaTransicoesLayout = new javax.swing.GroupLayout(VisualizaTransicoes);
        VisualizaTransicoes.setLayout(VisualizaTransicoesLayout);
        VisualizaTransicoesLayout.setHorizontalGroup(
            VisualizaTransicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisualizaTransicoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VisualizaTransicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VisualizaTransicoesLayout.createSequentialGroup()
                        .addComponent(labelVerTransicoes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollTransicoesCad))
                .addContainerGap())
        );
        VisualizaTransicoesLayout.setVerticalGroup(
            VisualizaTransicoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisualizaTransicoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVerTransicoes)
                .addGap(18, 18, 18)
                .addComponent(scrollTransicoesCad, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
        );

        buttonConverte.setText("Converter e Minimizar");
        buttonConverte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConverteActionPerformed(evt);
            }
        });

        labelEstadoInicial.setText("Estado inicial:");

        labelEstadoQ0.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonConverte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VisualizaTransicoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddTransicoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelEstadoInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelEstadoQ0)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelTitulo)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddTransicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEstadoInicial)
                            .addComponent(labelEstadoQ0))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VisualizaTransicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConverte, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void novoSimbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoSimbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoSimbActionPerformed

    private void buttonAddSimbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddSimbActionPerformed
        // TODO add your handling code here:
        if(!this.novoSimb.getText().isEmpty()){
            this.afnd.addSimbAlfabeto(this.novoSimb.getText().charAt(0));            
            this.novoSimb.setText("");
            this.atualizaListaAlfabeto();
        }//if
    }//GEN-LAST:event_buttonAddSimbActionPerformed

    private void atualizaListaAlfabeto(){
        int numSimb = this.afnd.getAlfabeto().size();
        String simbolos[] = new String[numSimb];
        for(int i = 0; i < numSimb;i++){
            simbolos[i] = this.afnd.getAlfabeto().get(i).toString();
        }
        this.listaSimbAlfabeto.setListData(simbolos);
    }
    
    private void buttonAddEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddEstadoActionPerformed
        // TODO add your handling code here:
        if(!this.novoQ.getText().isEmpty()){
            int novoEstado = Integer.parseInt(this.novoQ.getText());
            this.afnd.addEstado(novoEstado, Boolean.FALSE);
            this.novoQ.setText("");
            this.atualizaListaEstados();
        }
    }//GEN-LAST:event_buttonAddEstadoActionPerformed

    private void atualizaListaEstados(){
        int numSimb = this.afnd.getEstados().size();
        String simbolos[] = new String[numSimb];
        for(int i = 0; i < numSimb;i++){
            simbolos[i] = "q" + this.afnd.getEstados().get(i).toString();
        }
        this.listaEstadosAtual.setListData(simbolos);
        this.listaNovosEstados.setListData(simbolos);
        this.labelEstadoQ0.setText("q"+Integer.toString(this.afnd.getEstadoInicial()));
    }
    
    private void buttonAddTransicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddTransicaoActionPerformed
        // TODO add your handling code here:
        if(this.listaEstadosAtual.isSelectionEmpty()){
            return;
        }
        if(this.listaSimbAlfabeto.isSelectionEmpty()){
            return;
        }
        if(this.listaNovosEstados.isSelectionEmpty()){
            return;
        }
                
        int estadoAtual[] = new int[1];
        estadoAtual[0] = this.afnd.getEstados().get(this.listaEstadosAtual.getSelectedIndex());
        
        char simbLido = this.afnd.getAlfabeto().get(this.listaSimbAlfabeto.getSelectedIndex());
        
        int novosEstados[] = this.listaNovosEstados.getSelectedIndices();
        for(int i = 0; i < novosEstados.length; i++){
            novosEstados[i] = this.afnd.getEstados().get(novosEstados[i]);
        }
        
        this.afnd.addTransicao(estadoAtual, simbLido, novosEstados);
        this.atualizaListaTransicoes();
    }//GEN-LAST:event_buttonAddTransicaoActionPerformed

    private void atualizaListaTransicoes(){
        int numT = this.afnd.getTransicoes().size();
        String transicoes[] = new String[numT];
        
        for(int i = 0; i < numT; i++){
            transicoes[i] = this.afnd.getTransicoes().get(i).getTransicao();
        }
        this.listaTransicoesCad.setListData(transicoes);
    }
    
    private void buttonConverteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConverteActionPerformed
        // TODO add your handling code here:
        Janela.getInstancia().buttonConverteMenuGUIAction();
    }//GEN-LAST:event_buttonConverteActionPerformed

    private void buttonAddEstadoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddEstadoFinalActionPerformed
        // TODO add your handling code here:
        if(!this.novoF.getText().isEmpty()){
            int novoEstado = Integer.parseInt(this.novoF.getText());
            this.afnd.addEstado(novoEstado, Boolean.TRUE);
            this.novoF.setText("");
            this.atualizaListaEstados();
        }
    }//GEN-LAST:event_buttonAddEstadoFinalActionPerformed
    
    public void atualizaTudo(){
        atualizaListaAlfabeto();
        atualizaListaEstados();
        atualizaListaTransicoes();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddDados;
    private javax.swing.JPanel AddTransicoes;
    private javax.swing.JPanel VisualizaTransicoes;
    private javax.swing.JButton buttonAddEstado;
    private javax.swing.JButton buttonAddEstadoFinal;
    private javax.swing.JButton buttonAddSimb;
    private javax.swing.JButton buttonAddTransicao;
    private javax.swing.JButton buttonConverte;
    private javax.swing.JLabel labelAddF;
    private javax.swing.JLabel labelAddQ;
    private javax.swing.JLabel labelAddSimb;
    private javax.swing.JLabel labelAddTransicao;
    private javax.swing.JLabel labelEstadoAtual;
    private javax.swing.JLabel labelEstadoInicial;
    private javax.swing.JLabel labelEstadoQ0;
    private javax.swing.JLabel labelNovosEstados;
    private javax.swing.JLabel labelSimbLido;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVerTransicoes;
    private javax.swing.JList<String> listaEstadosAtual;
    private javax.swing.JList<String> listaNovosEstados;
    private javax.swing.JList<String> listaSimbAlfabeto;
    private javax.swing.JList<String> listaTransicoesCad;
    private javax.swing.JTextField novoF;
    private javax.swing.JTextField novoQ;
    private javax.swing.JTextField novoSimb;
    private javax.swing.JScrollPane scrollEstadosAtual;
    private javax.swing.JScrollPane scrollNovosEstados;
    private javax.swing.JScrollPane scrollSimbAlfabeto;
    private javax.swing.JScrollPane scrollTransicoesCad;
    // End of variables declaration//GEN-END:variables
}
