/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import source.AFD;

/**
 *
 * @author gabif
 */
public class ResultadosGUI extends javax.swing.JPanel {

    /**
     * Creates new form ResultadosGUI
     */
    private final AFD afd;
    
    public ResultadosGUI(AFD afd) {
        initComponents();
        this.afd = afd;
        this.atualizaListaAlfabeto();
        this.atualizaListaEstados();
        this.atualizaListaTransicoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelQuintuplaAFD = new javax.swing.JLabel();
        labelEstadoInicial = new javax.swing.JLabel();
        labelQ0 = new javax.swing.JLabel();
        labelAlfabeto = new javax.swing.JLabel();
        labelEstados = new javax.swing.JLabel();
        labelTransicoes = new javax.swing.JLabel();
        labelEstadosFinais = new javax.swing.JLabel();
        scrollSimbAlfabeto = new javax.swing.JScrollPane();
        listaSimbAlfabeto = new javax.swing.JList<>();
        scrollEstados = new javax.swing.JScrollPane();
        listaEstados = new javax.swing.JList<>();
        scrollTransicoes = new javax.swing.JScrollPane();
        listaTransicoes = new javax.swing.JList<>();
        scrollEstadosFinais = new javax.swing.JScrollPane();
        listaEstadosFinais = new javax.swing.JList<>();
        buttonAlteraAFN = new javax.swing.JButton();
        buttonResetaAFN = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTitulo.setText("Autômato Finito Determinístico (AFD) Gerado");

        labelQuintuplaAFD.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelQuintuplaAFD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelQuintuplaAFD.setText("AFD = ( ∑ , Q , δ , q0 , F)");

        labelEstadoInicial.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelEstadoInicial.setText("Estado Inicial (q0) = ");

        labelQ0.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelQ0.setText(".");

        labelAlfabeto.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelAlfabeto.setText("Alfabeto (∑)");

        labelEstados.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelEstados.setText("Estados (Q)");

        labelTransicoes.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelTransicoes.setText("Transições (δ)");

        labelEstadosFinais.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelEstadosFinais.setText("Estados Finais (F)");

        scrollSimbAlfabeto.setViewportView(listaSimbAlfabeto);

        scrollEstados.setViewportView(listaEstados);

        scrollTransicoes.setViewportView(listaTransicoes);

        scrollEstadosFinais.setViewportView(listaEstadosFinais);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelEstadoInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelQ0)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(labelQuintuplaAFD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(scrollSimbAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAlfabeto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(scrollEstados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEstados))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollTransicoes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(labelTransicoes, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(scrollEstadosFinais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEstadosFinais, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(14, 14, 14))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelAlfabeto, scrollSimbAlfabeto});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelEstados, scrollEstados});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelEstadosFinais, scrollEstadosFinais});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelQuintuplaAFD)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstadoInicial)
                    .addComponent(labelQ0))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelAlfabeto)
                        .addGap(18, 18, 18)
                        .addComponent(scrollSimbAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEstados)
                            .addComponent(labelTransicoes))
                        .addGap(18, 18, 18)
                        .addComponent(scrollEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(scrollTransicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelEstadosFinais)
                        .addGap(18, 18, 18)
                        .addComponent(scrollEstadosFinais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {scrollEstados, scrollEstadosFinais, scrollSimbAlfabeto, scrollTransicoes});

        buttonAlteraAFN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAlteraAFN.setText("Alterar AFN");
        buttonAlteraAFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlteraAFNActionPerformed(evt);
            }
        });

        buttonResetaAFN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonResetaAFN.setText("Resetar AFN");
        buttonResetaAFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetaAFNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelTitulo)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAlteraAFN)
                        .addGap(30, 30, 30)
                        .addComponent(buttonResetaAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonAlteraAFN, buttonResetaAFN});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelTitulo)
                .addGap(75, 75, 75)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAlteraAFN)
                    .addComponent(buttonResetaAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonAlteraAFN, buttonResetaAFN});

    }// </editor-fold>//GEN-END:initComponents

    private void buttonAlteraAFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlteraAFNActionPerformed
        // TODO add your handling code here:
        Janela.getInstancia().buttonAlteraResultadosGUIAction();
    }//GEN-LAST:event_buttonAlteraAFNActionPerformed

    private void buttonResetaAFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetaAFNActionPerformed
        // TODO add your handling code here:
        Janela.getInstancia().buttonResetaResultadosGUIAction();
    }//GEN-LAST:event_buttonResetaAFNActionPerformed

    @Override
    public void updateUI() {
        super.updateUI(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        if(this.afd != null)atualizaTudo();
    }
    
    private void atualizaListaAlfabeto(){
        int numSimb = this.afd.getAlfabeto().size();
        String simbolos[] = new String[numSimb];
        for(int i = 0; i < numSimb;i++){
            simbolos[i] = this.afd.getAlfabeto().get(i).toString();
        }
        this.listaSimbAlfabeto.setListData(simbolos);
    }
    
    private void atualizaListaEstados(){
        int numSimb = this.afd.getEstados().size();
        String simbolos[] = new String[numSimb];
        for(int i = 0; i < numSimb;i++){
            simbolos[i] = "q" + this.afd.getEstados().get(i).toString();
        }
        this.listaEstados.setListData(simbolos);
        
        numSimb = this.afd.getEstadosFinais().size();
        String simbolosFinais[] = new String[numSimb];
        for(int i = 0; i < numSimb;i++){
            simbolosFinais[i] = "q" + this.afd.getEstadosFinais().get(i).toString();
        }
        this.listaEstadosFinais.setListData(simbolosFinais);
        this.labelQ0.setText("q"+Integer.toString(this.afd.getEstadoInicial()));
    }
    
    private void atualizaListaTransicoes(){
        int numT = this.afd.getTransicoes().size();
        String transicoes[] = new String[numT];
        
        for(int i = 0; i < numT; i++){
            transicoes[i] = this.afd.getTransicoes().get(i).getTransicao();
        }
        
        this.listaTransicoes.setListData(transicoes);
    }

    public void atualizaTudo(){
        atualizaListaAlfabeto();
        atualizaListaEstados();
        atualizaListaTransicoes();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlteraAFN;
    private javax.swing.JButton buttonResetaAFN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAlfabeto;
    private javax.swing.JLabel labelEstadoInicial;
    private javax.swing.JLabel labelEstados;
    private javax.swing.JLabel labelEstadosFinais;
    private javax.swing.JLabel labelQ0;
    private javax.swing.JLabel labelQuintuplaAFD;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTransicoes;
    private javax.swing.JList<String> listaEstados;
    private javax.swing.JList<String> listaEstadosFinais;
    private javax.swing.JList<String> listaSimbAlfabeto;
    private javax.swing.JList<String> listaTransicoes;
    private javax.swing.JScrollPane scrollEstados;
    private javax.swing.JScrollPane scrollEstadosFinais;
    private javax.swing.JScrollPane scrollSimbAlfabeto;
    private javax.swing.JScrollPane scrollTransicoes;
    // End of variables declaration//GEN-END:variables
}
